### ISSUE TITLE
capture failed

### ISSUE THREAD

**Issue by unleashed7** [tateisu/ScreenShotButton#3]
I randomly get "capture failed illegalstateexception already resumed but proposed with update ok" errors at every 3-4th capture. Any solution?

![photo_2024-12-22_19-19-03](https://github.com/user-attachments/assets/445f2bc0-69fc-43c1-8b09-c74fe786eac4)

**Comment by unleashed7** [comment]
```
2024-12-22 19:35:36.779 2 D/ScreenShotButton/CaptureService: showButtonAll
2024-12-22 19:35:36.784 2 D/ScreenShotButton/ActMain: showButton
2024-12-22 19:35:36.819 2 W/ScreenShotButton/CaptureServiceStill: captureStart 1
2024-12-22 19:35:36.819 2 D/ScreenShotButton/CaptureService: showButtonAll
2024-12-22 19:35:36.824 2 D/ScreenShotButton/ActMain: showButton
2024-12-22 19:35:36.825 6890 W/ScreenShotButton/CaptureServiceStill: captureJob try 1
2024-12-22 19:35:36.825 6890 D/ScreenShotButton/Capture: updateMediaProjection caller=CaptureEnv.ctor
2024-12-22 19:35:36.827 6890 D/ScreenShotButton/Capture: MediaProjection registerCallback. addr=android.media.projection.MediaProjection@1ba7d8a
2024-12-22 19:35:36.827 6890 D/ScreenShotButton/Capture: 2ms create imageReader
2024-12-22 19:35:36.835 2 D/ScreenShotButton/CaptureService: showButtonAll
2024-12-22 19:35:36.838 2 D/ScreenShotButton/ActMain: showButton
2024-12-22 19:35:36.848 6878 D/ScreenShotButton/Capture: VirtualDisplay onResumed
2024-12-22 19:35:36.876 6890 D/ScreenShotButton/Capture: 49ms virtualDisplay created. waiting onResumed…
2024-12-22 19:35:36.877 2 D/ScreenShotButton/CaptureService: showButtonAll
2024-12-22 19:35:36.877 6890 E/ScreenShotButton/CaptureServiceStill: capture failed., IllegalStateException, Already resumed, but proposed with update OK
java.lang.IllegalStateException: Already resumed, but proposed with update OK
	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:447)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:412)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293)
	at jp.juggler.screenshotbutton.Capture$CaptureEnv$captureStill$$inlined$use$lambda$1.invokeSuspend(Capture.kt:766)
	at jp.juggler.screenshotbutton.Capture$CaptureEnv$captureStill$$inlined$use$lambda$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
	at jp.juggler.screenshotbutton.Capture$CaptureEnv.captureStill(Capture.kt:731)
	at jp.juggler.screenshotbutton.Capture$CaptureEnv.capture(Capture.kt:822)
	at jp.juggler.screenshotbutton.Capture.capture(Capture.kt:837)
	at jp.juggler.screenshotbutton.CaptureServiceBase$captureStart$1.invokeSuspend(CaptureServiceBase.kt:490)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2024-12-22 19:35:36.882 2 D/ScreenShotButton/ActMain: showButton
2024-12-22 19:35:41.032 6878 D/ScreenShotButton/Capture: MediaProjection onStop. addr=android.media.projection.MediaProjection@1ba7d8a
2024-12-22 19:35:41.033 2 I/ScreenShotButton/CaptureServiceStill: onDestroy start. stopReason=StopButton
2024-12-22 19:35:41.034 2 I/ScreenShotButton/CaptureServiceStill: onDestroy: captureJob join start
2024-12-22 19:35:41.034 2 I/ScreenShotButton/CaptureServiceStill: onDestroy: captureJob join end
2024-12-22 19:35:41.034 2 D/ScreenShotButton/Capture: release. caller=service.onDestroy
2024-12-22 19:35:41.034 2 D/ScreenShotButton/Capture: MediaProjection close.
2024-12-22 19:35:41.034 2 D/ScreenShotButton/CaptureService: showButtonAll
2024-12-22 19:35:41.034 2 D/ScreenShotButton/ActMain: showButton
2024-12-22 19:35:41.035 2 I/ScreenShotButton/CaptureServiceStill: onDestroy end
```

**Comment by tateisu** [comment]
since Android 14, we cant reuse capture intent. we have to prompt about
capture for each capture still image, or continues video capturing
implicitly on background and pick-up still when button tapped. latter
method very watse battery.

2024年12月23日(月) 4:37 unleashed7 ***@***.***>:

**Comment by tateisu** [comment]
maybe i have to archive this product.

2024年12月23日(月) 6:15 tateisu ***@***.***>:
